var annotated_dup =
[
    [ "Angle", "d2/d39/class_angle.html", "d2/d39/class_angle" ],
    [ "Arrangement", "d8/d46/class_arrangement.html", "d8/d46/class_arrangement" ],
    [ "Contact", "dd/d2a/class_contact.html", "dd/d2a/class_contact" ],
    [ "ContactElt", "da/d83/class_contact_elt.html", "da/d83/class_contact_elt" ],
    [ "ContactFunction", "d2/d41/class_contact_function.html", "d2/d41/class_contact_function" ],
    [ "ContactInterval", "db/dc7/class_contact_interval.html", "db/dc7/class_contact_interval" ],
    [ "Edge", "d7/d77/class_edge.html", "d7/d77/class_edge" ],
    [ "EdgeOrder", "d7/dae/class_edge_order.html", "d7/dae/class_edge_order" ],
    [ "Event", "d1/da9/class_event.html", "d1/da9/class_event" ],
    [ "Eventheap", "d3/d46/class_eventheap.html", "d3/d46/class_eventheap" ],
    [ "Face", "d5/d2a/class_face.html", "d5/d2a/class_face" ],
    [ "Feature", "d7/d76/class_feature.html", "d7/d76/class_feature" ],
    [ "glRegion", "d1/dd0/classgl_region.html", "d1/dd0/classgl_region" ],
    [ "Motion", "d4/d9a/class_motion.html", "d4/d9a/class_motion" ],
    [ "MotionElt", "d9/d86/class_motion_elt.html", "d9/d86/class_motion_elt" ],
    [ "Pair", "d2/d49/class_pair.html", "d2/d49/class_pair" ],
    [ "Part", "db/d16/class_part.html", "db/d16/class_part" ],
    [ "PEdge", "d6/d50/class_p_edge.html", "d6/d50/class_p_edge" ],
    [ "PEdgeOrder", "d9/dfc/class_p_edge_order.html", "d9/dfc/class_p_edge_order" ],
    [ "Point", "d0/d69/class_point.html", "d0/d69/class_point" ],
    [ "PsView", "d4/db7/class_ps_view.html", "d4/db7/class_ps_view" ],
    [ "PVertex", "de/d06/class_p_vertex.html", "de/d06/class_p_vertex" ],
    [ "RegIntersection", "d9/daf/class_reg_intersection.html", "d9/daf/class_reg_intersection" ],
    [ "Region", "df/d6c/class_region.html", "df/d6c/class_region" ],
    [ "Rootlist", "d6/d22/class_rootlist.html", "d6/d22/class_rootlist" ],
    [ "Segment", "dd/dd2/class_segment.html", "dd/dd2/class_segment" ],
    [ "SegmentNode", "d6/d4c/class_segment_node.html", "d6/d4c/class_segment_node" ],
    [ "SegmentOrder", "d9/d23/class_segment_order.html", "d9/d23/class_segment_order" ],
    [ "SegmentTree", "d6/da5/class_segment_tree.html", "d6/da5/class_segment_tree" ],
    [ "SimulateEvent", "dd/d15/class_simulate_event.html", "dd/d15/class_simulate_event" ],
    [ "Slice", "dd/d6c/class_slice.html", "dd/d6c/class_slice" ],
    [ "System", "d9/d16/class_system.html", "d9/d16/class_system" ],
    [ "SystemWindow", "da/dee/class_system_window.html", "da/dee/class_system_window" ],
    [ "Triangle", "d2/d28/class_triangle.html", "d2/d28/class_triangle" ]
];